const chapters=['六題必做','有時間再玩'];
const storeKey='tokyo.ai.senior.v2';let saved={};let timer;let current=1;
try{saved=JSON.parse(localStorage.getItem(storeKey)||'{}');if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={}}catch{}
const preferences={'輕鬆散步':'喜歡輕鬆散步','品嚐美食':'喜歡品嚐美食','逛街購物':'喜歡逛街購物','帶家人同行':'想帶家人一起旅行'};
const aiTools={'ChatGPT':'https://chatgpt.com/','Gemini':'https://gemini.google.com/','Claude':'https://claude.ai/'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(t){const box=document.getElementById('toast');box.textContent=t;box.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>box.classList.remove('show'),4500)}
function persist(){try{localStorage.setItem(storeKey,JSON.stringify(saved))}catch{notice('完成紀錄目前只保留在這次開啟期間。')}}
function progress(){const n=COURSE.filter(e=>e.cat===0&&saved['done'+e.id]).length;document.getElementById('progressText').textContent=n+' / 6';document.getElementById('progress').value=n}
function promptFor(e){const pref=preferences[saved.preference]||preferences['輕鬆散步'];if(e.id===1)return `我想去東京玩三天，${pref}，希望少走路、多休息。請用簡單的繁體中文，給我三個旅行想法。`;if(e.id===3)return `請先幫我們安排東京的一天行程，先假設住在上野。我們${pref}，最多去兩個區域，少走路、多休息。用表格列出去哪裡、做什麼。不確定的時間和票價寫「待查」。`;return e.prompt}
function route(id,scroll=true){if(!COURSE.some(e=>e.id===id))return;current=id;const hash='#lesson-'+String(id).padStart(2,'0');if(location.hash!==hash){location.hash=hash;return}render(scroll)}
function render(scroll=true){
 const e=COURSE.find(e=>e.id===current),group=COURSE.filter(x=>x.cat===e.cat),index=group.indexOf(e),isNblm=e.tool==='NotebookLM',isImage=e.tool==='繪圖 AI';
 const toolOptions=isImage?['Gemini','ChatGPT']:Object.keys(aiTools);const selected=toolOptions.includes(saved[isImage?'imageTool':'aiTool'])?saved[isImage?'imageTool':'aiTool']:toolOptions[0];
 const url=isNblm?'https://notebooklm.google.com/':aiTools[selected];
 document.querySelectorAll('[data-cat]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.cat===e.cat)));
 document.getElementById('chapterTitle').textContent=chapters[e.cat];document.getElementById('chapterCount').textContent=group.length+' 題';
 document.getElementById('lessons').innerHTML=group.map(x=>`<button data-lesson="${x.id}" ${x.id===current?'aria-current="step"':''}><span class="num">${String(x.number).padStart(2,'0')}</span><span>${esc(x.title)}</span>${saved['done'+x.id]?'<span class="done-mark" aria-label="已完成">✓</span>':''}</button>`).join('');
 const sourceBlock=[5,9,11].includes(e.id)?`<section class="source-block"><h3>${e.id===11?'先放入簡報內容':'準備好的六頁內容'}</h3><p>不用自己打字。可直接用示範內容；也可以複製 AI 剛才寫好的六頁內容。</p><button id="copySample">複製六頁示範內文</button>${isNblm?'<a class="tool-button" href="https://notebooklm.google.com/" target="_blank" rel="noopener noreferrer">開啟 NotebookLM ↗</a><p>建立筆記本 → 新增來源 → 貼上文字 → 插入。</p>':''}</section>`:'';
 document.getElementById('lesson').innerHTML=`<div class="meta"><span>${e.cat===0?'必做':'選做'} ${String(e.number).padStart(2,'0')} / ${chapters[e.cat]}</span><span>約 ${e.time} 分</span></div><h2 id="lessonTitle">${esc(e.title)}</h2><p class="learning-point">${esc(e.point)}</p><ol class="steps">${e.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>${e.id===1||e.id===3?`<fieldset class="preferences"><legend>你喜歡哪一種？點一下就好</legend>${Object.keys(preferences).map(p=>`<button data-pref="${p}" aria-pressed="${(saved.preference||'輕鬆散步')===p}">${p}</button>`).join('')}</fieldset>`:''}${sourceBlock}<div class="prompt"><div class="prompt-head"><label for="promptText">${isNblm&&e.id!==9?'接著，設定生成內容':'這樣跟 AI 說'}<small>不用改字，直接複製</small></label></div><textarea id="promptText" readonly aria-label="可直接複製的提示詞" rows="5">${esc(promptFor(e))}</textarea><div class="copy-actions">${!isNblm?`<label class="tool-choice">使用工具 <select id="toolChoice">${toolOptions.map(t=>`<option ${t===selected?'selected':''}>${t}</option>`).join('')}</select></label>`:''}<button id="copyPrompt">① 複製提示詞</button><a id="openTool" class="tool-button" href="${url}" target="_blank" rel="noopener noreferrer">② 開啟 ${isNblm?'NotebookLM':selected} ↗</a><p>${isNblm?(e.id===9?'③ 在筆記本的對話框貼上，按送出。':`③ 在工作室選「${e.id===10?'資訊圖表':'簡報'}」的自訂功能，貼上後生成。`):'③ 在 AI 輸入框貼上，按送出。接續練習請回到原本的對話。'}</p></div></div>${e.followups?.length?`<section class="followups"><h3>${isNblm&&e.id!==9?'想換個樣式？':'想再改一點？'}</h3><p>${isNblm&&e.id!==9?'點一下複製，再貼到生成內容的自訂欄位。':'點一下複製，再貼回同一段 AI 對話。'}</p><div>${e.followups.map((f,i)=>`<button data-followup="${i}">複製：${esc(f[0])}</button>`).join('')}</div></section>`:''}<p class="tip">${esc(e.tip)}</p><section class="checks"><h3>做到這裡就完成</h3><ul>${e.checks.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section><div class="lesson-bottom"><label class="finish"><input id="done" type="checkbox" ${saved['done'+e.id]?'checked':''}>我已完成這一題</label><div class="actions"><button id="prev" class="quiet" ${index===0?'disabled':''}>上一題</button><button id="next" ${index===group.length-1&&e.cat===1?'disabled':''}>${index===group.length-1&&e.cat===0?'看看選做練習':'下一題 →'}</button></div></div>${e.id===11?'<p class="end-note">六題做完了！打開簡報，跟身旁的人分享你的東京旅行想法。</p>':''}`;
 document.getElementById('copyPrompt').onclick=()=>copy(document.getElementById('promptText').value);
 document.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>{saved.preference=b.dataset.pref;persist();document.querySelectorAll('[data-pref]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.getElementById('promptText').value=promptFor(e)});
 const chooser=document.getElementById('toolChoice');if(chooser)chooser.onchange=()=>{saved[isImage?'imageTool':'aiTool']=chooser.value;persist();const link=document.getElementById('openTool');link.href=aiTools[chooser.value];link.textContent='② 開啟 '+chooser.value+' ↗'};
 const sample=document.getElementById('copySample');if(sample)sample.onclick=()=>copy(SAMPLE,'已複製六頁內容，請貼到 NotebookLM 的新增來源。');
 document.querySelectorAll('[data-followup]').forEach(b=>b.onclick=()=>copy(e.followups[+b.dataset.followup][1],isNblm&&e.id!==9?'已複製，請貼到生成內容的自訂欄位。':'已複製追問，請貼回同一段 AI 對話。'));
 document.getElementById('done').onchange=ev=>{saved['done'+e.id]=ev.target.checked;persist();progress();const b=document.querySelector(`[data-lesson="${e.id}"]`);b.querySelector('.done-mark')?.remove();if(ev.target.checked)b.insertAdjacentHTML('beforeend','<span class="done-mark" aria-label="已完成">✓</span>')};
 document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>route(+b.dataset.lesson));document.getElementById('prev').onclick=()=>index>0&&route(group[index-1].id);document.getElementById('next').onclick=()=>{if(index<group.length-1)route(group[index+1].id);else if(e.cat===0)route(COURSE.find(x=>x.cat===1).id)};progress();if(scroll){document.getElementById('lesson').scrollIntoView({block:'start'});document.getElementById('lesson').focus({preventScroll:true})}
}
async function copy(text,message='已複製，請切換到 AI 工具貼上。'){try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(text);notice(message)}catch{const box=document.getElementById('manualCopy');box.value=text;document.getElementById('copyDialog').showModal();box.focus();box.select()}}
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>route(COURSE.find(e=>e.cat===+b.dataset.cat).id));document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>copy(b.dataset.material==='brief'?MATERIAL:SAMPLE));document.getElementById('sampleText').textContent=SAMPLE;document.getElementById('selectCopy').onclick=()=>{const el=document.getElementById('manualCopy');el.focus();el.select()};document.getElementById('closeCopy').onclick=()=>document.getElementById('copyDialog').close();document.getElementById('reset').onclick=()=>{if(confirm('清除這個初階版的完成紀錄？')){Object.keys(saved).filter(k=>k.startsWith('done')).forEach(k=>delete saved[k]);persist();render(false);notice('完成紀錄已清除。')}};
function fromHash(scroll){if(location.hash==='#lesson'){if(scroll)document.getElementById('lesson').focus();return}const m=location.hash.match(/^#lesson-(\d+)$/);current=m&&COURSE.some(e=>e.id===+m[1])?+m[1]:1;render(scroll)}window.addEventListener('hashchange',()=>fromHash(true));fromHash(false);
