const chapters=['破冰體驗','文字與簡報內容','圖像與貼圖','NotebookLM'];
const storeKey='tokyo.ai.beginner.v1';let saved={};let drafts={};let timer;let current=1;
try{saved=JSON.parse(localStorage.getItem(storeKey)||'{}');if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={}}catch{}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(t){let box=document.getElementById('toast');box.textContent=t;box.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>box.classList.remove('show'),3200)}
function persist(){try{localStorage.setItem(storeKey,JSON.stringify(saved))}catch{notice('目前無法儲存，完成紀錄只保留在這次開啟期間。')}}
function progress(){const n=COURSE.filter(e=>saved['done'+e.id]).length;document.getElementById('progressText').textContent=n+' / 12';document.getElementById('progress').value=n}
function route(id,scroll=true){const entry=COURSE.find(e=>e.id===id);if(!entry)return;current=id;const hash='#lesson-'+String(id).padStart(2,'0');if(location.hash!==hash){location.hash=hash;return}render(scroll)}
function render(scroll=true){const e=COURSE.find(e=>e.id===current);document.querySelectorAll('[data-cat]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.cat===e.cat)));document.getElementById('chapterTitle').textContent=chapters[e.cat];const group=COURSE.filter(x=>x.cat===e.cat);document.getElementById('chapterCount').textContent=group.length+' 題';document.getElementById('lessons').innerHTML=group.map(x=>`<button data-lesson="${x.id}" ${x.id===current?'aria-current="step"':''}><span class="num">${String(x.id).padStart(2,'0')}</span><span>${esc(x.title)}</span>${saved['done'+x.id]?'<span class="done-mark" aria-label="已完成">✓</span>':''}</button>`).join('');
document.getElementById('lesson').innerHTML=`<div class="meta"><span>練習 ${String(e.id).padStart(2,'0')} / ${chapters[e.cat]}</span><span>${esc(e.tool)} · 約 ${e.time} 分</span></div><h2 id="lessonTitle">${esc(e.title)}</h2><p class="learning-point">${esc(e.point)}</p><ol class="steps">${e.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><div class="prompt"><div class="prompt-head"><label for="promptText">這樣跟 AI 說<small>可以直接修改，再按複製</small></label><button id="copyPrompt">複製提示詞</button></div><textarea id="promptText" spellcheck="false" aria-label="可修改的提示詞" rows="${Math.min(13,Math.max(5,e.prompt.split('\n').length+1))}">${esc(drafts[e.id]??e.prompt)}</textarea></div>${e.extra?`<details class="extra"><summary>${esc(e.extra.label)}</summary><p>${esc(e.extra.text)}</p><button id="copyExtra">複製追問</button></details>`:''}<p class="tip">${esc(e.tip)}</p><fieldset class="checks"><legend>做到這裡就完成</legend>${e.checks.map((t,i)=>`<label><input type="checkbox" data-check="${e.id}-${i}" ${saved['check'+e.id+'-'+i]?'checked':''}>${esc(t)}</label>`).join('')}</fieldset><div class="lesson-bottom"><label class="finish"><input id="done" type="checkbox" ${saved['done'+e.id]?'checked':''}>我已完成這一題</label><div class="actions"><button id="prev" class="quiet" ${e.id===1?'disabled':''}>上一題</button><button id="next" ${e.id===12?'disabled':''}>下一題 →</button></div></div>${e.id===12?'<p class="end-note">最後一步：打開你的簡報，向身旁的人分享東京旅行構想。</p>':''}`;
 document.getElementById('promptText').addEventListener('input',ev=>drafts[e.id]=ev.target.value);document.getElementById('copyPrompt').onclick=()=>copy(document.getElementById('promptText').value);if(e.extra)document.getElementById('copyExtra').onclick=()=>copy(e.extra.text);document.getElementById('done').onchange=ev=>{saved['done'+e.id]=ev.target.checked;persist();progress();document.querySelectorAll('[data-lesson]').forEach(b=>{const mark=b.querySelector('.done-mark');if(+b.dataset.lesson===e.id){if(ev.target.checked&&!mark)b.insertAdjacentHTML('beforeend','<span class="done-mark" aria-label="已完成">✓</span>');if(!ev.target.checked&&mark)mark.remove()}})};
 document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{saved['check'+x.dataset.check]=x.checked;persist()});document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>route(+b.dataset.lesson));document.getElementById('prev').onclick=()=>route(e.id-1);document.getElementById('next').onclick=()=>route(e.id+1);progress();if(scroll){document.getElementById('lesson').scrollIntoView({block:'start'});document.getElementById('lesson').focus({preventScroll:true})}}
async function copy(text){try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(text);notice('已複製，切換到 AI 工具貼上即可。')}catch{const box=document.getElementById('manualCopy');box.value=text;document.getElementById('copyDialog').showModal();box.focus();box.select()}}
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>route(COURSE.find(e=>e.cat===+b.dataset.cat).id));document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>copy(b.dataset.material==='brief'?MATERIAL:SAMPLE));document.getElementById('sampleText').textContent=SAMPLE;document.getElementById('selectCopy').onclick=()=>{const el=document.getElementById('manualCopy');el.focus();el.select()};document.getElementById('closeCopy').onclick=()=>document.getElementById('copyDialog').close();document.getElementById('reset').onclick=()=>{if(confirm('清除這個初階版的完成紀錄？')){saved={};persist();render(false);notice('完成紀錄已清除。')}};
function fromHash(scroll){if(location.hash==='#lesson'){if(scroll)document.getElementById('lesson').focus();return}const m=location.hash.match(/^#lesson-(\d+)$/);current=m&&COURSE.some(e=>e.id===+m[1])?+m[1]:1;render(scroll)}window.addEventListener('hashchange',()=>fromHash(true));fromHash(false);
